# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Saverio <saverio.brancaccio@gmail.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:15+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-08-30 12:41+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language: it\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Italian\n"

#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""
"La dimensione virtuale di %(base)s %(base_size)s è maggiore della dimensione "
"del disco di root dell'istanza %(size)s"

#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""
"%(scheme)s è registrato due volte come modulo. %(module_name)s non sarà "
"usato."

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on %(host)s"
msgstr ""
"Aggregato %(aggregate_id)s: stato non recuperabile durante l'operazione in "
"%(host)s"

msgid "An error occurred while refreshing the network cache."
msgstr "Si è verificato un errore durante l'aggiornamento della cache di rete."

#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr "Il collegamento dei dispositivi PCI %(dev)s a %(dom)s è fallito."

msgid "Cannot cleanup migration files"
msgstr "Impossibile ripulire i file di migrazione"

#, python-format
msgid "Cannot reboot instance: %s"
msgstr "Impossibile riavviare l'istanza: %s"

#, python-format
msgid "Caught error: %s"
msgstr "Intercettato errore: %s"

msgid "Compute driver option required, but not specified"
msgstr "L'opzione compute driver è obbligatoria, ma non è stata specificata"

#, python-format
msgid "Connection to libvirt failed: %s"
msgstr "Connessione a libvirt non riuscita: %s"

#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Impossible fare il bind verso %(host)s:%(port)s"

#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "Impossibile rimuovere tmpdir: %s"

msgid "Couldn't communicate with any cells"
msgstr "Impossibile comunicare con alcuna cella"

#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr "Impossibile comunicare con la cella '%s'"

#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr "Impossibile fare l'unmount del GlusterFS share %s"

#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr "Impossibile fare unmount del NFS share %s"

#, python-format
msgid "Creating config drive failed with error: %s"
msgstr "Creazione unità config non riuscita, con errore: %s"

#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr "Scollegamento della scheda di rete fallito. Eccezione: %s"

#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to default "
"handler '%(default_handler)s'"
msgstr ""
"L'handler del download '%(handler)s' ha lanciato un'eccezione, impossibile "
"tornare all'handler di default '%(default_handler)s'"

#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""
"Il driver non è riuscito a legare il volume %(volume_id)s su %(mountpoint)s"

msgid "Environment variable 'NETWORK_ID' must be set."
msgstr "La variabile d'ambiente 'NETWORK_ID' deve essere impostata."

#, python-format
msgid "Error defining a domain with XML: %s"
msgstr "Errore nella definizione di un dominio tramite XML: %s"

#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr "Errore durante l'eliminazione degli elementi conntrack per %s"

#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Errore durante la distribuzione dell'istanza %(instance)s nel nodo baremetal "
"%(node)s."

#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr "Errore nell'abilitare la modalità hairpin tramite XML: %s"

#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr "Errore dall'ultimo host: %(last_host)s (nodo %(last_node)s): %(exc)s"

#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr "Errore di libvirt durante la distruzione. Code=%(errcode)s Error=%(e)s"

#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr ""
"Errore di libvirt durante la rimozione di una definizione. Code=%(errcode)s "
"Error=%(e)s"

#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr ""
"Errore di libvirt durante l'annullamento del filtro. Code=%(errcode)s Error="
"%(e)s"

#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr "Errore durante l'inserimento di dati nell'immagine %(img_id)s (%(e)s)"

#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr "Impossibile istanziare %(provider)s: %(exception)s"

#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr "Errore nell'avvio di un dominio definito tramite XML: %s"

msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""
"Si è verificato un errore durante l'operazione volume_snapshot_create, invio "
"dello stato di errore a Cinder."

msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""
"Si è verificato un errore durante l'operazione di volume_snapshot_delete, "
"invio dello stato di errore a Cinder."

#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr "Errore in '%(path)s' durante il controllo di I/O diretto: '%(ex)s'"

#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Errore durante la preparazione dell'istanza %(instance)s sul nodo baremetal "
"%(node)s."

#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr ""
"Errore durante il rilascio del DHCP per gli IP %(address)s con MAC "
"%(mac_address)s"

#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr "Errore di pianificazione istanze %(instance_uuids)s"

#, python-format
msgid "Error starting xvp: %s"
msgstr "Errore durante l'avvio di xvp: %s"

msgid "Error trying to Rescue Instance"
msgstr "Errore nel tentativo di recupero dell'istanza"

msgid "Error trying to reschedule"
msgstr "Errore durante tentativo di eseguire una nuova pianificazione"

#, python-format
msgid "Error while trying to clean up image %s"
msgstr "Errore durante il tentativo di pulitura dell'immagine %s"

#, python-format
msgid "Error: %s"
msgstr "Errore: %s"

#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr "Eccezione durante l'invio dell'evento %(event)s: %(ex)s"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Eccezione durante la gestione della risorsa: %s"

msgid "Exception in string format operation"
msgstr "Eccezione nell'operazione di formattazione della stringa"

#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Eccezione durante l'esecuzione di %(name)s %(type)s-hook: %(obj)s"

msgid "Exception while creating table."
msgstr "Eccezione durante la creazione della tabella."

#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr "Estensione del disco virtuale fallita con errore: %s"

#, python-format
msgid "Failed removing net device: '%s'"
msgstr "Impossibile rimuovere il dispositivo di rete: '%s'"

msgid "Failed storing info cache"
msgstr "Impossibile memorizzare le informazioni nella cache"

msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the "
"compute node semaphore"
msgstr ""
"Impossibile allocare dispositivi PCI per l'istanza. Annullo "
"dell'assegnazione dei dispositivi e rimessa degli stessi nei pool. Ciò non "
"dovrebbe accadere perchè lo scheduler dovrebbe avere informazioni accurate e "
"l'allocazione durante le richieste è controllata attraverso un evento di "
"attesa sul semaforo del compute node"

msgid "Failed to allocate network(s)"
msgstr "Impossibile allorare rete(i)"

#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr "Impossibile legare %(volume_id)s su %(mountpoint)s"

#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr "Impossibile legare il volume al punto di mount: %s"

#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr ""
"Impossibile cambiare lo stato della vm di %(instance_name)s a %(req_state)s"

msgid "Failed to check if instance shared"
msgstr "Impossibile verificare se l'istanza sia condivisa"

#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr "Impossibile ripulire la directory %(target)s: %(e)s"

msgid "Failed to cleanup snapshot."
msgstr "Impossibile pulire lo snapshot."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Impossibile impostare le prenotazioni %s"

msgid "Failed to complete a deletion"
msgstr "Impossibile completare l'eliminazione"

#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""
"Impossibile connettersi al volume %(volume_id)s con il volume su "
"%(mountpoint)s"

#, python-format
msgid ""
"Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""
"Impossibile copiare l'immagine presente in cache %(source)s verso %(dest)s "
"per il ridimensionamento: %(error)s"

msgid "Failed to deallocate networks"
msgstr "Impossibile deallocare le reti"

#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr "Impossibile decodificare %(image_location)s in %(image_path)s"

#, python-format
msgid "Failed to destroy instance: %s"
msgstr "Distruzione istanza non riuscita: %s"

#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr "Impossibile scollegare il volume %(volume_id)s da %(mp)s"

#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr "Impossibile scaricare %(image_location)s in %(image_path)s"

msgid "Failed to fetch glance image"
msgstr "Impossibile recuperare l'immagine glance"

#, python-format
msgid "Failed to find an SR for volume %s"
msgstr "Impossibile trovare un repositorio di storage per il volume: %s"

#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr "Impossibile rimuovere il repositorio di storage per il volume %s"

#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""
"Impossibile generare il controllo dell'utilizzo per l'istanza sull'host %s"

#, python-format
msgid "Failed to get compute_info for %s"
msgstr "Impossibile ottenere compute_info per %s"

msgid "Failed to get default networks"
msgstr "Impossibile ottenere le reti predefinite"

#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr "Impossibile ottenere i metadati per l'id dell'istanza: %s"

msgid "Failed to get nw_info"
msgstr "Impossibile ottenere nw_info"

#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr "Impossibile istanziare l'handler di download per %(scheme)s"

#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr "Impossibile caricare %(cfgfile)s: %(ex)s"

#, python-format
msgid "Failed to load %s"
msgstr "Impossibile caricare %s"

#, python-format
msgid "Failed to load %s-api"
msgstr "Impossibile caricare %s-api"

#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': %(errors)s"
msgstr ""
"Impossibile montare file system del contenitore '%(image)s' in '%(target)s': "
"%(errors)s"

msgid "Failed to notify cells of BDM destroy."
msgstr "Impossibile notificare alle celle la rimozione del BDM."

msgid "Failed to notify cells of BDM update/create."
msgstr "Impossibile notificare alle celle la creazione/aggiornamento del BDM."

msgid "Failed to notify cells of bw_usage update"
msgstr "Impossibile notificare alle celle l'aggiornamento di bw_usage"

msgid "Failed to notify cells of instance fault"
msgstr "Impossibile notificare alle celle l'errore dell'istanza"

msgid "Failed to notify cells of instance info cache update"
msgstr ""
"Impossibile notificare alle celle l'aggiornamento delle informazioni della "
"cache sull'istanza"

#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "Impossibile rimuovere %(base_file)s, l'errore era %(error)s"

#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""
"Impossibile richiedere Ironic per la fornitura dell'istanza %(inst)s: "
"%(reason)s"

#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""
"Impossibile recuperare i metadati di crittografia per il volume "
"%(volume_id)s: %(exception)s"

msgid "Failed to retrieve ephemeral encryption key"
msgstr "Impossibile recuperare la chiave di crittografia temporanea"

msgid "Failed to revert crashed migration"
msgstr "Impossibile riprendere la migrazione interrotta in modo anomalo"

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Impossibile richiamare le prenotazioni %s"

msgid "Failed to send state update notification"
msgstr "Invio della notifica di aggiornamento dello stato non riuscita"

msgid "Failed to send updated snapshot status to volume service."
msgstr ""
"Impossibile inviare lo stato di snapshot aggiornato al servizio di volume."

msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr ""
"Impossibile impostare il nome dell'istanza utilizzando "
"multi_instance_display_name_template."

#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr ""
"Avvio di %(name)s non riuscito in %(host)s:%(port)s con il supporto SSL"

msgid "Failed to start instance"
msgstr "Impossibile avviare l'istanza"

msgid "Failed to stop instance"
msgstr "Impossibile fermare l'istanza"

#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr ""
"Impossibile fare lo swap del volume %(old_volume_id)s per %(new_volume_id)s"

#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr ""
"Impossibile l'estrazione di file tar %(image_location)s in %(image_path)s"

msgid "Failed to update usages bulk deallocating floating IP"
msgstr "Impossibile aggiornare gli utilizzi di bulk disallocando l'IP mobile"

msgid "Failed to update usages deallocating fixed IP"
msgstr "Impossibile aggiornare utilizzi deallocazione IP fisso"

msgid "Failed to update usages deallocating floating IP"
msgstr "Impossibile aggiornare gli utilizzi disallocando l'IP mobile"

msgid "Failed to update usages deallocating network."
msgstr "Impossibile aggiornare utilizzi deallocazione rete."

msgid "Failed to update usages deallocating security group"
msgstr "Impossibile aggiornare utilizzi deallocazione gruppo di sicurezza"

msgid "Failed to update usages deallocating server group"
msgstr "Impossibile aggiornare gli usi deallocando il gruppo di server."

#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr "Impossibile caricare %(image_location)s in %(image_path)s"

msgid "Failed to write configuration file"
msgstr "Impossibile scrivere il file di configurazione"

msgid "Failed to write inbound.csr"
msgstr "Impossibile scrivere inbound.csr"

msgid "Failed while plugging vif"
msgstr "Fallimento durante il collegamento del vif"

msgid "Failed while unplugging vif"
msgstr "Errore durante scollegamento vif"

msgid "Failure prepping block device"
msgstr "Fallimento durante la preprazione del block device"

msgid "Failure while cleaning up attached VDIs"
msgstr "Errore durante la ripulitura delle VDI collegate"

#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr ""
"Eccezione grave durante l'esecuzione di %(name)s %(type)s-hook: %(obj)s"

msgid "Guest does not have a console available"
msgstr "Guest non dispone di una console disponibile"

msgid "Host is member of a pool, but DB says otherwise"
msgstr "L'host è membro di un pool, ma il DB dice il contrario"

#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""
"Il nome dell'host è cambiato da %(old)s a %(new)s. E' richiesto un restart "
"affinchè la modifica abbia effetto."

#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""
"La dimensione dell'immagine %(size)d supera il limite permesso dall'istanza "
"%(allowed_size)d"

#, python-format
msgid ""
"Instance compute service state on %s expected to be down, but it was up."
msgstr ""
"Stato dell'istanza del servizio di calcolo  su %s previsto come attivo ma è "
"stato trovato passivo."

msgid "Instance failed block device setup"
msgstr "L'istanza non è riuscita a configurare l'unità di blocco"

#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr ""
"L'istanza non è riuscita a configurare la rete in %(attempts)d tentativi"

msgid "Instance failed to spawn"
msgstr "L'istanza non è riuscita a generare"

#, python-format
msgid "Interface %s not found"
msgstr "Interfaccia %s non trovata"

#, python-format
msgid "Invalid server_string: %s"
msgstr "stringa_server non valida %s"

#, python-format
msgid "Live Migration failure: %s"
msgstr "Fallimento di Live Migration: %s"

msgid "Migrate Receive failed"
msgstr "Migrazione di Receive non riuscita"

msgid "Migrate Send failed"
msgstr "Migrazione di Send non riuscita"

#, python-format
msgid "Migration %s is not found during confirmation"
msgstr "La migrazione %s non è stata trovata durante la conferma"

#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly failed."
msgstr ""
"La migrazione dell'istanza %(instance_id)s verso l'host %(dest)s è fallita "
"inaspettatamente."

#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr ""
"Errore NBD - l'unmount precedente non si è ripulito /var/lock/qemu-nbd-%s."

#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. args="
"%(args)r"
msgstr ""
"NON IMPLEMENTATO: la chiamata del %(method)s non è supportata dall'agent. "
"args=%(args)r"

msgid "Network driver option required, but not specified"
msgstr "L'opzione driver di rete è obbligatoria, ma non è specificata"

#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr ""
"Errore di Neutron durante l'aggiunta delle regole al gruppo di sicurezza %s"

#, python-format
msgid "Neutron Error creating security group %s"
msgstr "Errore di Neutron nella creazione del gruppo di sicurezza %s"

#, python-format
msgid "Neutron Error getting security group %s"
msgstr "Errore di Neutron durante la lettura del gruppo di sicurezza %s"

msgid "Neutron Error getting security groups"
msgstr "Errore di Neutron durante la lettura dei gruppi di sicurezza"

#, python-format
msgid "Neutron Error unable to delete %s"
msgstr "Errore di Neutron impossibile eliminare %s"

#, python-format
msgid "Neutron Error updating security group %s"
msgstr "Errore di Neutron durante l'aggiornamento del gruppo di sicurezza %s"

msgid "Neutron Error:"
msgstr "Errore di Neutron:"

#, python-format
msgid "Neutron Error: %s"
msgstr "Errore di Neutron: %s"

#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr ""
"Neutron ha riportato un fallimento per l'evento %(event)s relativo "
"all'istanza %(uuid)s"

#, python-format
msgid "Neutron error creating port on network %s"
msgstr "Errore di Neutron durante la creazione della porta su rete %s"

#, python-format
msgid "No save handler for %s"
msgstr "Nessun handler di salvataggio per %s"

msgid ""
"Periodic sync_power_state task had an error while processing an instance."
msgstr ""
"Il task periodico sync_power_state ha avuto un errore durante l'elaborazione "
"dell'istanza."

msgid "Periodic task failed to offload instance."
msgstr "Il task periodico non è riuscito a fare l'offload dell'istanza."

#, python-format
msgid "Pool-Join failed: %s"
msgstr "Pool-Join fallito: %s"

#, python-format
msgid "Pool-eject failed: %s"
msgstr "Pool-eject fallito: %s"

#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr "Pool-set_name_label fallito: %s"

#, python-format
msgid "Pre live migration failed at %s"
msgstr "Migrazione pre live fallita su %s"

#, python-format
msgid "Returning exception %s to caller"
msgstr "Sollevando eccezione %s al chiamante"

msgid "Service error occurred during cleanup_host"
msgstr "Errore di servizio durante il cleanup_host"

msgid "Setting instance vm_state to ERROR"
msgstr "Impostazione dello stato di istanza a ERRORE"

msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr ""
"Qualcosa non è andato a buon fine durante l'eliminazione dello snapshot "
"dall'istanza sospesa."

#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr "TIMEOUT: timeout della chiamata a %(method)s. args=%(args)r"

#, python-format
msgid "Temporary directory is invalid: %s"
msgstr "La directory temporanea non è valida: %s"

#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. args="
"%(args)r"
msgstr ""
"La chiamata dell'agente verso %(method)s ha restituito una risposta non "
"valida: %(ret)r. args=%(args)r"

#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr "La chiamata a %(method)s restituito un errore: %(e)s."

#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr "La chiamata a %(method)s ha restituito un errore: %(e)s. args=%(args)r"

#, python-format
msgid "Unable to access floating IP %s"
msgstr "Impossibile accedere all'IP mobile %s"

#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Impossibile legare il volume all'istanza %s"

msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""
"Impossibile creare lo snapshot della VM, fallimento dell'operazione "
"volume_snapshot."

msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""
"Impossibile creare lo snapshot di VM inattiva, nuovo tentativo in corso con "
"impostazione di inattivtà disabilitata."

#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr "Impossibile eseguire %(cmd)s. Eccezione: %(exception)s"

msgid "Unable to get updated status"
msgstr "Impossibile ottenere lo stato aggiornato"

msgid "Unable to load the virtualization driver"
msgstr "Impossibile caricare il driver di virtualizzazione"

#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr "Impossibile migrare la VM %(vm_ref)s da %(host)s"

#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: %(server)s."
msgstr ""
"Impossibile ottenere RRD XML per VM %(vm_uuid)s con i dettagli del server: "
"%(server)s."

#, python-format
msgid "Unable to parse rrd of %s"
msgstr "Impossibile analizzare rrd di %s"

#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr "Impossibile recuperare le policy di storage con nome: %s"

#, python-format
msgid "Unable to set up pool: %s."
msgstr "Impossibile configurare il pool: %s."

msgid "Unexpected build failure, not rescheduling build."
msgstr ""
"Errore di generazione non previsto, la generazione non sarà riproposta."

msgid "Unexpected exception in API method"
msgstr "Eccezione imprevista nel metodo API"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr ""
"Cella sconosciuta '%(cell_name)s' durante il tentativo di aggiornare le "
"funzionalità"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr ""
"Cella sconosciuta '%(cell_name)s' durante il tentativo di aggiornare le "
"capacità"

#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr "Contenuto sconosciuto in Connection_info/access_mode: %s"

msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""
"Tentativo di ripresa della VM ma il vm_state risulta essere SHELVED o "
"SHELVED_OFFLOADED"

#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""
"Il volume %s è associato all'istanza ma per esso non è stato trovato alcun "
"repositorio di storage"

#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: %(ex)s"
msgstr ""
"Al caricamento del modulo %(module_str)s si verifica il seguente errore: "
"%(ex)s"

msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances on. "
"Please check your configuration (e.g. set a default SR for the pool) and/or "
"configure the flag 'sr_matching_filter'."
msgstr ""
"XenAPI non riesce a trovare un repositorio di storage su cui installare le "
"instanze guest. Si prega di controllare la propria configurazione (e.g. "
"impostare un repositorio di storage per il pool) e/o configurare il flag "
"'sr_matching_filter'."

#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr "_migrate_disk_resizing_up fallito. Ripristino della vm due_to: %s."

#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr "allocate_port_for_instance ha restituito le porte %(ports)s"

msgid "attaching network adapter failed."
msgstr "Impossibile collegare l'adattatore di rete."

msgid "detaching network adapter failed."
msgstr "collegamento dell'adattatore di rete non riuscito."

msgid "error during stop() in sync_power_state."
msgstr "errore durante l'arresto() in sync_power_state."

#, python-format
msgid "error opening rbd image %s"
msgstr "Errore nell'apertura dell'immagine rbd %s"

#, python-format
msgid "killing radvd threw %s"
msgstr "interruzione di radvd %s"

msgid "nbd module not loaded"
msgstr "modulo nbd non caricato"

#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. Bad "
"upgrade or db corrupted?"
msgstr ""
"lo stato è SCONOSCIUTO per vm_state=%(vm_state)s task_state=%(task_state)s. "
"Aggiornamento non corretto o db danneggiato?"
