# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Ettore Atalan <atalanttore@googlemail.com>, 2014
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:15+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-10-01 06:49+0000\n"
"Last-Translator: Frank Kloeker <eumel@arcor.de>\n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: German\n"

msgid "\"Look for the VDIs failed"
msgstr "\"Nachschau der VDIs fehlgeschlagen"

#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""
"%(base)s virtuelle Festplatte %(base_size)s größer als die Größe der "
"Varianten Root Festplatte %(size)s"

#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""
"%(scheme)s ist schon registriert als Modul. %(module_name)s ist nicht in "
"Benutzung."

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on %(host)s"
msgstr ""
"Aggregat %(aggregate_id)s: nicht zu behebender Status während der Operation "
"an %(host)s"

msgid "An error occurred while refreshing the network cache."
msgstr ""
"Ein Fehler ist während des Aktualisierens des Netzwerk Caches aufgetreten."

#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr "Anhängen PCI Gerät %(dev)s an %(dom)s fehlgeschlagen."

msgid "Cannot cleanup migration files"
msgstr "Konnte Migrationsdateien nicht aufräumen"

#, python-format
msgid "Cannot reboot instance: %s"
msgstr "Instanz kann nicht neu gestartet werden: %s"

#, python-format
msgid "Caught error: %s"
msgstr "Fehler abgefangen: %s"

msgid "Compute driver option required, but not specified"
msgstr "Compute Treiber Option erforderlich, aber nicht spezifiziert"

#, python-format
msgid "Connection to libvirt failed: %s"
msgstr "Verbindung zu libvirt fehlgeschlagen: %s"

#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Keine Bindung an %(host)s:%(port)s möglich"

msgid "Could not decode scheduler options"
msgstr "Konnte Optionen für den Scheduler nicht entschlüsseln"

#, python-format
msgid ""
"Could not disconnect encrypted volume %(volume)s. If dm-crypt device is "
"still active it will have to be destroyed manually for cleanup to succeed."
msgstr ""
"Konnte verschlüsselte Festplatte %(volume)s nicht trennen. Wenn dm-crypt auf "
"dem Gerät weiter aktiv ist, muß die Trennung manuell erfolgen."

#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "tmpdir konnte nicht entfernt werden: %s"

#, python-format
msgid "Could not start encryption for disk %(device)s: %(exception)s"
msgstr ""
"Konnte Verschlüsselung nicht starten für Festplatte %(device)s: %(exception)s"

#, python-format
msgid "Could not stat scheduler options file %(filename)s"
msgstr ""
"Konnte den Status nicht feststellen der Scheduler-Optionsdatei  %(filename)s"

msgid "Couldn't communicate with any cells"
msgstr "Konnte nicht mit irgendeiner Zelle kommunizieren"

#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr "Konnte nicht mit der Zelle kommunizieren '%s'"

#, python-format
msgid "Couldn't lookup app: %s"
msgstr "Konnte Applikation nicht auslesen: %s"

#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr "Die GlusterFS-Freigabe %s konnte nicht ausgehängt werden"

#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr "Die NFS-Freigabe %s konnte nicht ausgehängt werden"

#, python-format
msgid "Couldn't unmount the Quobyte Volume at %s"
msgstr "Konnte das Quobyte Volume nicht abhängen von %s"

#, python-format
msgid "Couldn't unmount the share %s"
msgstr "Konnte die Freigabe %s nicht aushängen"

#, python-format
msgid "Creating config drive failed with error: %s"
msgstr "Erstellung Konfigurationsfestplatte fehlgeschlagen: %s"

msgid "DB error"
msgstr "Datenbankfehler"

msgid "Destroy VM failed"
msgstr "Zerstören der VM fehlgeschlagen"

msgid "Destroy instance failed"
msgstr "Zerstören der Instanz fehlgeschlagen"

#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr "Abhängen des Netzwerkadapters fehlgeschlagen. Ausnahme:  %s"

#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to default "
"handler '%(default_handler)s'"
msgstr ""
"Download Handler '%(handler)s' erreichte eine Ausnahme, falle zurück auf die "
"Standardsteuerung '%(default_handler)s'"

msgid "Download image error"
msgstr "Download Abbild Fehler"

#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr ""
"Treiber fehlgeschlagen zum  Anhängen des Datenträgers %(volume_id)s an "
"%(mountpoint)s"

msgid "Environment variable 'NETWORK_ID' must be set."
msgstr "Umgebungsvariable 'NETWORK_ID' muss gesetzt sein."

#, python-format
msgid "Error defining a domain with XML: %s"
msgstr "Fehler beim Definieren einer Domain mit XML: %s"

#, python-format
msgid "Error defining a secret with XML: %s"
msgstr "Fehler beim Definieren eines Geheimnisses mit XML: %s"

#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr "Fehler beim Löschen der Einträge für %s"

#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Fehler bei der Erstellung der Instanz %(instance)s auf dem BareMetal-Knoten "
"%(node)s."

#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr "Fehler beim Aktivieren des Hairpin-Mode mit XML: %s"

#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr "Fehler vom letzten Host: %(last_host)s (node %(last_node)s): %(exc)s"

#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr "Fehler von  libvirt beim Löschen. Code=%(errcode)s Fehler=%(e)s"

#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr "Fehler von  libvirt beim Undefinieren. Code=%(errcode)s Fehler=%(e)s"

#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr "Fehler von  libvirt beim Unfiltrieren. Code=%(errcode)s Fehler=%(e)s"

#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr "Fehler beim Einfügen von Daten in das Abbild %(img_id)s (%(e)s)"

#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr "Fehler beim instanziieren %(provider)s: %(exception)s"

#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr "Fehler beim Starten einer definierten Domain mit XML: %s"

msgid "Error locating next hop for message"
msgstr "Fehler beim Lokalisieren der nächsten Adresse für die Nachricht"

msgid "Error locating next hops for message"
msgstr "Fehler beim Lokalisieren der nächsten Adressen für die Nachricht"

msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""
"Ein Fehler ist aufgetreten bei volume_snapshot_create, sende Fehlerstatus zu "
"Cinder."

msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""
"Ein Fehler ist aufgetreten bei volume_snapshot_delete, sende Fehlerstatus zu "
"Cinder."

#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr "Fehler an '%(path)s' bei der Überprüfung direct I/O: '%(ex)s'"

#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Fehler bei der Vorbereitung zur Erstellung der Instanz %(instance)s auf dem "
"BareMetal-Knoten %(node)s."

msgid "Error processing message locally"
msgstr "Fehler bei der lokalen Nachrichtenverarbeitung"

#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr ""
"Fehler bei der DHCP-Freigabe der IP %(address)s mit MAC %(mac_address)s"

#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr "Fehler bei der Planung der Instanzen %(instance_uuids)s"

msgid "Error sending message to next hops."
msgstr "Fehler beim Senden der Nachricht zur nächsten Adresse."

#, python-format
msgid "Error starting xvp: %s"
msgstr "Fehler beim Starten von xvp: %s"

msgid "Error trying to Rescue Instance"
msgstr "Fehler beim Versuch des Wiederherstellens der Instanz"

msgid "Error trying to reschedule"
msgstr "Fehler beim Versuch der Neuplanung"

msgid "Error waiting for responses from neighbor cells"
msgstr "Fehler beim Warten auf Antwort von den Nachbarzellen"

#, python-format
msgid "Error while trying to clean up image %s"
msgstr "Fehler beim Versuch das Abbild %s zu löschen"

#, python-format
msgid "Error writing to %(path)s: %(exception)s"
msgstr "Fehler beim Schreiben zu %(path)s: %(exception)s"

#, python-format
msgid "Error: %s"
msgstr "Fehler: %s"

#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr "Ausnahme bei der Erledigung des Ereignisses %(event)s: %(ex)s"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Ausnahmebehandlungsressource: %s"

msgid "Exception in string format operation"
msgstr "Ausnahme bei Zeichenfolgeformatoperation"

msgid "Exception loading extension"
msgstr "Ausnahme beim Laden der Erweiterung"

#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Ausnahme beim Lauf %(name)s %(type)s-hook: %(obj)s"

msgid "Exception while creating table."
msgstr "Ausnahme beim Anlegen einer Tabelle."

#, python-format
msgid "Exception while waiting completion of volume snapshots: %s"
msgstr "Ausnahme beim Warten auf Fertigstellung des Datenträgerabbilds: %s"

#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr "Erweitern der virtuellen Festplatte fehlgeschlagen mit Fehler: %s"

#, python-format
msgid "Failed removing bridge device: '%s'"
msgstr "Löschen des Brückengerätes fehlgeschlagen: '%s'"

#, python-format
msgid "Failed removing net device: '%s'"
msgstr "Löschen des Netzgerätes fehlgeschlagen: '%s'"

msgid "Failed storing info cache"
msgstr "Fehler beim Speichern in den Zwischenspeicher"

msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the "
"compute node semaphore"
msgstr ""
"Zuweisung von PCI Geräten zur Instanz fehlgeschlagen. Nicht zugewiesene "
"Geräte sind zurück im Pool. Das sollte nicht passieren, wenn der Scheduler "
"genaue Informationen hat, und die Zuweisung der Aufgaben im ausgeschalteten "
"Zustand des Computer-Knotens erfolgt"

msgid "Failed to allocate network(s)"
msgstr "Netz(e) konnte(n) nicht zugeordnet werden"

#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr "Anhängen fehlgeschlagen von %(volume_id)s an %(mountpoint)s"

#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr "Einhängen des Datenträgers fehlgeschlagen am Einhängepunkt: %s"

#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr ""
"Fehler beim Wechseln des VM-Status von %(instance_name)s nach %(req_state)s"

msgid "Failed to check if instance shared"
msgstr "Fehler bei der Überprüfung, ob die Instanz freigegeben ist"

#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr "Fehler beim Aufräumen des Verzeichnisses %(target)s: %(e)s"

msgid "Failed to cleanup snapshot."
msgstr "Fehler beim Aufräumen der Schattenkopie."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Fehler beim Übergeben der Reservierung %s"

msgid "Failed to complete a deletion"
msgstr "Fehler beim vollständigen Löschen"

#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""
"Verbindung des Datenträgers fehlgeschlagen %(volume_id)s mit Datenträger an "
"%(mountpoint)s"

#, python-format
msgid ""
"Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""
"Fehler beim Kopieren des zwischengespeicherten Abbildes %(source)s zu "
"%(dest)s für Größenänderung: %(error)s"

msgid "Failed to deallocate networks"
msgstr "Fehler beim Freigeben des Netzwerks"

#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr "Entschlüsseln von %(image_location)s zu %(image_path)s fehlgeschlagen"

#, python-format
msgid "Failed to destroy instance: %s"
msgstr "Fehler bei der Zerstörung der Instanz: %s"

#, python-format
msgid "Failed to detach %(device_name)s. Exception: %(exc)s"
msgstr "Abhängen fehlgeschlagen %(device_name)s. Ausnahme: %(exc)s"

#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr "Abhängen fehlgeschlagen von %(volume_id)s von %(mp)s"

#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr "Download %(image_location)s zu %(image_path)s fehlgeschlagen"

msgid "Failed to fetch glance image"
msgstr "Abruf des Glance Abbildes fehlgeschlagen"

#, python-format
msgid "Failed to find an SR for volume %s"
msgstr "Konnte kein SR finden für Datenträger %s"

#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr "Fehler beim Vergessen des SR für Datenträger %s"

#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr ""
"Fehler bei der Generierung des Verwendungsreports für Instanz an Host %s"

#, python-format
msgid "Failed to get compute_info for %s"
msgstr "Fehler beim Beziehen compute_info von %s"

msgid "Failed to get default networks"
msgstr "Fehler beim Abruf der Standardnetzwerke"

#, python-format
msgid ""
"Failed to get instance id for metadata request, provider %(provider)s "
"networks %(networks)s requester %(requester)s. Error: %(error)s"
msgstr ""
"Fehler beim Abruf der Instanz-ID , Provider %(provider)s Netzwerke "
"%(networks)s Anforderer %(requester)s. Fehler: %(error)s"

#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr "Fehler beim Abruf der Metadaten für Instanz-ID: %s"

msgid "Failed to get nw_info"
msgstr "Fehler beim Abruf von nw_info"

#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr "Instanziieren der Download-Steuerung fehlgeschlagen für %(scheme)s"

#, python-format
msgid ""
"Failed to kill process %(pid)s due to %(reason)s, while deleting the "
"instance."
msgstr ""
"Fehler beim Töten des Prozesses %(pid)s durch %(reason)s, beim Löschen der "
"Instanz."

#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr "Fehler beim Laden von %(cfgfile)s: %(ex)s"

#, python-format
msgid "Failed to load %s"
msgstr "Fehler beim Laden von %s"

#, python-format
msgid "Failed to load %s-api"
msgstr "Fehler beim Laden %s-Api"

#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': %(errors)s"
msgstr ""
"Fehler beim Einhängen des Container-Dateisystems '%(image)s' an "
"'%(target)s': %(errors)s"

msgid "Failed to notify cells of BDM destroy."
msgstr "Fehler bei der Benachrichtigung der Zellen von BDM über Zerstörung."

msgid "Failed to notify cells of BDM update/create."
msgstr ""
"Fehler bei der Benachrichtigung der Zellen von BDM über Aktualisierung/"
"Erstellung."

msgid "Failed to notify cells of bw_usage update"
msgstr "Fehler bei der Notifizierung der Zelle von bw_usage"

msgid "Failed to notify cells of instance fault"
msgstr "Notifizierung der Zellen über Instanzfehler fehlgeschlagen"

msgid "Failed to notify cells of instance info cache update"
msgstr ""
"Notifizierung der Zellen über Aktualisisierung der "
"Instanzinformationsspeicher fehlgeschlagen"

#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "Fehler beim Löschen %(base_file)s, Fehler war %(error)s"

#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr ""
"Ironic-Anfrage fehlgeschlagen bei der Erstellung der Instanz %(inst)s: "
"%(reason)s"

#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""
"Fehler beim Empfangen der verschlüsselten Metadaten für Datenträger "
"%(volume_id)s: %(exception)s"

msgid "Failed to retrieve ephemeral encryption key"
msgstr "Bezug des flüchtigen Verschlüsselungsschlüssel fehlgeschlagen"

msgid "Failed to revert crashed migration"
msgstr "Fehler beim Zurücknehmen der abgestürzten Migration"

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Fehler beim Rücksetzen der Reservierung %s"

msgid "Failed to rollback quota for failed finish_resize"
msgstr "Quota zurückrollen fehlgeschlagen für fehlgeschlagenes finish_resize"

#, python-format
msgid "Failed to send message to cell: %(next_hop)s"
msgstr "Fehler beim Senden der Nachricht zur Zelle: %(next_hop)s"

msgid "Failed to send state update notification"
msgstr "Fehler beim Senden der Notifizierung zur Statusänderung"

msgid "Failed to send updated snapshot status to volume service."
msgstr ""
"Fehler beim Senden des Aktualisierungsstatus der Schattenkopie an den "
"Datenträgerdienst."

msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr "Fehler beim Setzen des Instanz-Namens instance_display_name_template."

#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr ""
"Fehler beim Starten %(name)s auf %(host)s:%(port)s mit SSL-Unterstützung"

msgid "Failed to start instance"
msgstr "Fehler beim Starten der Instanz"

msgid "Failed to stop instance"
msgstr "Anhalten der Instanz fehlgeschlagen"

#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr ""
"Tausch des Datenträgers fehlgeschlagen von %(old_volume_id)s nach "
"%(new_volume_id)s"

msgid "Failed to teardown container filesystem"
msgstr "Fehler beim Einreissen des Container-Dateisystems"

msgid "Failed to umount container filesystem"
msgstr "Fehler beim Aushängen des Container-Dateisystems"

msgid "Failed to unpause instance"
msgstr "Aufheben des Pausierens fehlgeschlagen."

#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr "Auspacken von %(image_location)s zu %(image_path)s fehlgeschlagen"

msgid "Failed to update usages bulk deallocating floating IP"
msgstr "Fehler bei der Aktualisierung der Verbrauchsmenge von Floating-IP"

msgid "Failed to update usages deallocating fixed IP"
msgstr ""
"Aktualisierungsfehler der Verwendungen der freigegebenen festen IP-Adressen"

msgid "Failed to update usages deallocating floating IP"
msgstr "Aktualisierungsfehler der Verwendungen der freigegebenen Floating IPs"

msgid "Failed to update usages deallocating network."
msgstr ""
"Fehler bei der Aktualisierung der Verwendung der freigegebenen Netzwerke"

msgid "Failed to update usages deallocating security group"
msgstr ""
"Fehler bei der Aktualisierung der Verwendung der freigegebenen "
"Sicherheitsgruppen"

msgid "Failed to update usages deallocating server group"
msgstr ""
"Fehler bei der Aktualisierung der Verwendung der freigegebenen Servergruppen"

#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr "Hochladen von  %(image_location)s zu %(image_path)s fehlgeschlagen"

msgid "Failed to write configuration file"
msgstr "Fehler beim Schreiben der Konfigurationsdatei"

msgid "Failed to write inbound.csr"
msgstr "Schreiben der inbound.csr ist fehlgeschlagen"

msgid "Failed while plugging ib hostdev vif"
msgstr "Fehler beim Anschliessen von ib hostdev vif"

msgid "Failed while plugging vif"
msgstr "Fehler beim Anschliessen von vif"

msgid "Failed while unplugging ib hostdev vif"
msgstr "Fehler beim Trennen von ib hostdev vif"

msgid "Failed while unplugging vif"
msgstr "Fehler beim Trennen von vif"

msgid "Failure prepping block device"
msgstr "Fehler bei der Vorbereitung des Blockgerätes"

msgid "Failure while cleaning up attached VDIs"
msgstr "Fehler beim Aufräumen der angehangenen VDIs"

#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Schwere Ausnahme beim Lauf %(name)s %(type)s-hook: %(obj)s"

msgid "Guest does not have a console available"
msgstr "Gast hat keine Konsole verfügbar"

msgid "Host is member of a pool, but DB says otherwise"
msgstr "Host ist Mitglied eines Pools, aber die Datenbank sagt etwas anderes"

#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""
"Hostname hat sich geändert von %(old)s zu %(new)s. Ein Neustart ist "
"erforderlich."

#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""
"Abbildgröße %(size)d überschritt die erlaubte Variantengröße %(allowed_size)d"

#, python-format
msgid ""
"Instance compute service state on %s expected to be down, but it was up."
msgstr ""
"Instanz  Compute Dienstestatus an %s erwartet als ausser Betrieb, ist aber "
"in Betrieb."

msgid "Instance failed block device setup"
msgstr "Instanz fehlgeschlagen bei der Einrichtung des Blockgerätes"

#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr ""
"Netzwerkeinrichtung der Instanz fehlgeschlagen nach %(attempts)d Versuche(n)"

msgid "Instance failed to spawn"
msgstr "Erzeugen der Instanz fehlgeschlagen"

#, python-format
msgid "Interface %s not found"
msgstr "Schnittstelle %s nicht gefunden"

#, python-format
msgid "Invalid server_string: %s"
msgstr "Ungültiger server_string: %s"

#, python-format
msgid "Live Migration failure: %s"
msgstr "Live-Migration fehlgeschlagen: %s"

msgid "Live migration failed."
msgstr "Live-Migration fehlgeschlagen."

msgid "Migrate Receive failed"
msgstr "Migration enthielt Fehler"

msgid "Migrate Send failed"
msgstr "Migration sendet Fehler"

#, python-format
msgid "Migration %s is not found during confirmation"
msgstr "Migration %s nicht gefunden bei der Rückmeldung"

#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly failed."
msgstr ""
"Migration von Instanz %(instance_id)s zu Host %(dest)s unerwartet "
"fehlgeschlagen."

msgid "Migration operation has aborted"
msgstr "Migration Operation abgebrochen"

#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr ""
"NBD Fehler - vorheriges Aushängen hat /var/lock/qemu-nbd-%s nicht gelöscht."

#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. args="
"%(args)r"
msgstr ""
"NOT IMPLEMENTED: Der Aufruf %(method)s wird vom Agenten nicht unterstützt. "
"args=%(args)r"

msgid "Network driver option required, but not specified"
msgstr "Netzwerktreiber-Option ist erforderlich, aber nicht angegeben"

#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr "Neutron Fehler beim Hinzufügen von Regeln zur Sicherheitsgruppe %s"

#, python-format
msgid "Neutron Error creating security group %s"
msgstr "Neutron Fehler bei der Erstellung der Sicherheitsgruppe %s"

#, python-format
msgid "Neutron Error getting security group %s"
msgstr "Neutron Fehler beim Abruf der Sicherheitsgruppe %s"

msgid "Neutron Error getting security groups"
msgstr "Neutron Fehler beim Abruf der Sicherheitsgruppen"

#, python-format
msgid "Neutron Error unable to delete %s"
msgstr "Neutron Fehler beim Löschen %s"

#, python-format
msgid "Neutron Error updating security group %s"
msgstr "Neutron Fehler bei der Aktualisierung der Sicherheitsgruppe %s"

msgid "Neutron Error:"
msgstr "Neutron-Fehler:"

#, python-format
msgid "Neutron Error: %s"
msgstr "Neutron-Fehler: %s"

#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr "Neutron berichtet Fehler an Ereignis %(event)s für Instanz %(uuid)s"

#, python-format
msgid "Neutron error creating port on network %s"
msgstr "Neutron Fehler bei der Porterstellung für Netzwerk %s"

#, python-format
msgid "No compute node record for host %s"
msgstr "Kein Compute-Knoteneintrag für Host %s"

#, python-format
msgid "No save handler for %s"
msgstr "Keine sichere Steuerung für %s"

msgid "Not all properties needed are implemented in the compute driver"
msgstr ""
"Nicht alle Eigenschaften brauchen in den Compute Treiber implementiert werden"

msgid ""
"Periodic sync_power_state task had an error while processing an instance."
msgstr ""
" Regelmässiger Auftrag sync_power_state hat Fehler bei der Verarbeitung der "
"Instanz."

msgid "Periodic task failed to offload instance."
msgstr "Regelmässiger Auftrag zum Ausladen der Instanz fehlgeschlagen."

msgid "Plugin config_file get_val failed"
msgstr "Plugin config_file get_val Fehler"

#, python-format
msgid "Pool-Join failed: %s"
msgstr "Pool-Vereinigung fehlgeschlagen: %s"

#, python-format
msgid "Pool-eject failed: %s"
msgstr "Pool-Trennung fehlgeschlagen: %s"

#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr "Pool-set_name_label Fehler: %s"

#, python-format
msgid "Pre live migration failed at %s"
msgstr "Vor-Live-Migration fehlgeschlagen an %s"

msgid "Read/Write data failed"
msgstr "Lesen/Schreiben von Daten fehlgeschlagen"

#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr "Angefragte VM Generation %s, aber zur Verfügung steht VHD statt VHDX."

#, python-format
msgid "Returning exception %s to caller"
msgstr "Ausnahme %s wird an Aufrufenden zurückgegeben"

msgid "Service error occurred during cleanup_host"
msgstr "Dienstefehler aufgetreten beim cleanup_host"

msgid "Setting instance vm_state to ERROR"
msgstr "Setze Instanz vm_state auf FEHLER"

msgid "Shutting down VM (cleanly) failed."
msgstr "Herunterfahren der VM (sauber) fehlgeschlagen."

msgid "Shutting down VM (hard) failed"
msgstr "Herunterfahren der VM (hart) fehlgeschlagen."

msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr ""
"Beim Löschen der Schattenkopie der eingestellten Instanz hat etwas nicht "
"geklappt."

#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr ""
"ZEITÜBERSCHREITUNG: Der Aufruf nach %(method)s hat die Zeit überschritten. "
"args=%(args)r"

#, python-format
msgid "Temporary directory is invalid: %s"
msgstr "Temporäres Verzeichnis ist ungültig: %s"

#, python-format
msgid "The Quobyte volume at %s is still in use."
msgstr "Das Quobyte Abbild auf %s ist weiter in Benutzung."

#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. args="
"%(args)r"
msgstr ""
"Der Agentenaufruf %(method)s gab eine ungültige Antwort zurück: %(ret)r. "
"args=%(args)r"

#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr "Der Aufruf zu %(method)s gab einen Fehler zurück: %(e)s."

#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr "Der Aufruf zu %(method)s gab einen Fehler zurück: %(e)s. args=%(args)r"

msgid "Transfer data failed"
msgstr "Datenübertragung fehlgeschlagen"

#, python-format
msgid "Unable to access floating IP %s"
msgstr "Zugriff nicht möglich auf Floating-IP %s"

msgid "Unable to access the rescue disk"
msgstr "Kein Zugriff auf die Rettungsplatte"

#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Nicht möglich Volumen zur Instanze %s hinzuzufügen"

#, python-format
msgid "Unable to clear device ID for port '%s'"
msgstr "Aufräumen nicht möglich der Geräte-ID für Port '%s'"

msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""
"Erstellen der VM Schattenkopie nicht möglich, volume_snapshot Operation "
"fehlgeschlagen."

msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""
"Erstellen der stillgelegten VM Schattenkopie nicht möglich, versuche "
"stattdessen mit deaktivierter Stillegung."

msgid "Unable to destroy VBD"
msgstr "Zerstören VBD fehlgeschlagen"

#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr "Ausführen von %(cmd)s nicht möglich. Ausnahme: %(exception)s"

msgid "Unable to find SR from VBD"
msgstr "Konnte kein SR finden für VBD"

msgid "Unable to find SR from VDI"
msgstr "Konnte kein SR finden für VDI"

msgid "Unable to get record of VDI"
msgstr "Konnte keinen EIntrag für VDI beziehen"

msgid "Unable to get updated status"
msgstr "Aktualisierter Status konnte nicht abgeholt werden"

msgid "Unable to introduce VDI for SR"
msgstr "Bekanntmachung VDI an SR nicht möglich"

msgid "Unable to introduce VDI on SR"
msgstr "Bekanntmachung VDI an SR nicht möglich"

msgid "Unable to load the virtualization driver"
msgstr "Virtualisierungstreiber konnte nicht geladen werden"

#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr "Migration der VM %(vm_ref)s von %(host)s nicht möglich"

#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: %(server)s."
msgstr ""
"Konnte kein RRD XML erhalten für VM %(vm_uuid)s mit Serverdetails: "
"%(server)s."

#, python-format
msgid "Unable to parse rrd of %s"
msgstr "Zerlegen des RRD von %s fehlgeschlagen"

#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr "Konnte Speicherregeln mit Namen %s nicht beziehen"

#, python-format
msgid "Unable to set up pool: %s."
msgstr "Pool-Einrichtung nicht möglich: %s."

msgid "Unable to unplug VBD"
msgstr "Entfernen VBD fehlgeschlagen"

#, python-format
msgid "Unable to update instance VNIC index for port %s."
msgstr "Instanzaktualisierung VNIC Index nicht möglich für Port %s."

msgid "Unexpected build failure, not rescheduling build."
msgstr "Unerwarteter Fehler beim Aufbau, wird nicht neu geplant."

#, python-format
msgid "Unexpected error while checking process %(pid)s."
msgstr "Unerwarteter Fehler bei der Überprüfung des Prozesses %(pid)s."

msgid "Unexpected exception in API method"
msgstr "Unerwartete Ausnahme in API-Methode"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr ""
"Unbekannte Zelle '%(cell_name)s' beim Versuch die Resourcen zu aktualisieren"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr ""
"Unbekannte Zelle '%(cell_name)s' beim Versuch die Resourcen zu aktualisieren"

#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr "Unbekannter Inhalt in connection_info/access_mode: %s"

msgid "Unshelve attempted but an error has occurred"
msgstr "Versuch zurückgestellt, aber ein Fehler ist aufgetreten"

msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""
"Versuch zurückgestellt aber vm_state ist nicht SHELVED oder SHELVED_OFFLOADED"

msgid "Vifs plug failed"
msgstr "Vifs plug fehlgeschlagen"

#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""
"Datenträger %s ist verbunden mit der Instanz aber kein SR wurde dafür "
"gefunden."

#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""
"Datenträger nicht schreibbar. Bitte Dateirechte erweitern. Einhängepunkt: %s"

#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: %(ex)s"
msgstr ""
"Beim Laden des Moduls %(module_str)s ist folgender Fehler aufgetreten: %(ex)s"

msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances on. "
"Please check your configuration (e.g. set a default SR for the pool) and/or "
"configure the flag 'sr_matching_filter'."
msgstr ""
"XenAPI konnte kein Speicherverzeichnis zur Installation der Gastinstanz "
"finden. Bitte überprüfen Sie die Konfiguration (z.B. Standard SR für den "
"Pool) und/oder konfigurieren Sie das Flag 'sr_matching_filter'."

msgid "_migrate_disk_resizing_down failed. Restoring orig vm"
msgstr ""
"_migrate_disk_resizing_down fehlgeschlagen. Stelle Original VM wieder her"

#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr ""
"_migrate_disk_resizing_up fehlgeschlagen. Stelle Original-VM wieder her "
"due_to: %s."

#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr "allocate_port_for_instance gab zurück %(ports)s Ports"

msgid "attaching network adapter failed."
msgstr "Einhängen des Netzwerkadapters fehlgeschlagen."

msgid "detaching network adapter failed."
msgstr "Aushängen des Netzwerkadapters fehlgeschlagen."

msgid "error during stop() in sync_power_state."
msgstr "Fehler während stop() in sync_power_state."

#, python-format
msgid "error opening rbd image %s"
msgstr "Fehler beim Öffnen des RBD Abbildes %s"

#, python-format
msgid "image %(volume)s in pool %(pool)s has snapshots, failed to remove"
msgstr ""
"Abbild %(volume)s in Pool %(pool)s hat Schattenkopien, kann nicht gelöscht "
"werden"

#, python-format
msgid "kill -HUP dnsmasq threw %s"
msgstr "kill -HUP dnsmasq warf %s"

#, python-format
msgid "killing radvd threw %s"
msgstr "killing radvd warf %s"

msgid "nbd module not loaded"
msgstr "nbd-Modul nicht geladen"

msgid "set_admin_password failed"
msgstr "set_admin_password fehlgeschlagen"

#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. Bad "
"upgrade or db corrupted?"
msgstr ""
"Status ist UNBEKANNT von vm_state=%(vm_state)s task_state=%(task_state)s. "
"Fehler in der Aktualisierung oder Datenbank korrupt?"
