# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
#
# Translators:
# Zbyněk Schwarz <zbynek.schwarz@gmail.com>, 2015
# Andreas Jaeger <jaegerandi@gmail.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: nova 14.0.0.0b3.dev750\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-08-25 06:15+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-12-21 12:12+0000\n"
"Last-Translator: Zbyněk Schwarz <zbynek.schwarz@gmail.com>\n"
"Language: cs\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
"Generated-By: Babel 2.0\n"
"X-Generator: Zanata 3.7.3\n"
"Language-Team: Czech\n"

msgid "\"Look for the VDIs failed"
msgstr "\"Hledání VBD selhalo"

#, python-format
msgid ""
"%(base)s virtual size %(base_size)s larger than flavor root disk size "
"%(size)s"
msgstr ""
"%(base)s virtuální velikost %(base_size)s větší než velikost kořenového "
"disku konfigurace %(size)s "

#, python-format
msgid ""
"%(scheme)s is registered as a module twice. %(module_name)s is not being "
"used."
msgstr ""
"%(scheme)s je jako modul registrováno dvakrát. %(module_name)s se nebude "
"používat."

#, python-format
msgid ""
"Aggregate %(aggregate_id)s: unrecoverable state during operation on %(host)s"
msgstr ""
"Agregát %(aggregate_id)s: neobnovitelný stav během provádění operace na "
"%(host)s"

msgid "An error occurred while deallocating network."
msgstr "Při rušení přidělení sítě nastala chyba."

msgid "An error occurred while refreshing the network cache."
msgstr "Při obnově mezipaměti sítě došlo k chybě."

#, python-format
msgid "Attach volume failed to %(instance_name)s: %(exn)s"
msgstr "Připojení svazku k %(instance_name)s selhalo: %(exn)s"

#, python-format
msgid "Attaching PCI devices %(dev)s to %(dom)s failed."
msgstr "Připojování zařízení PCI %(dev)s do %(dom)s selhalo."

#, python-format
msgid "Attaching network adapter failed. Exception: %s"
msgstr "Připojování síťového adaptéru selhalo. Výjimka: %s"

msgid "Cannot cleanup migration files"
msgstr "Nelze vyčistit soubory přesunu"

#, python-format
msgid ""
"Cannot log in target %(target_iqn)s. Unsupported iSCSI authentication "
"method: %(auth_method)s."
msgstr ""
"Nelze se přihlásit v cíli %(target_iqn)s. Nepodporovaný způsob věření ISCSI: "
"%(auth_method)s."

#, python-format
msgid "Cannot reboot instance: %s"
msgstr "Nelze restartovat instanci: %s"

#, python-format
msgid "Caught error: %s"
msgstr "Zachycena chyba: %s"

msgid "Compute driver option required, but not specified"
msgstr "Je vyžadována volba ovladače výpočtu, která ale není zadána"

#, python-format
msgid ""
"Connection between volume %(vol)s and host %(host)s might have succeeded, "
"but attempt to terminate connection has failed. Validate the connection and "
"determine if manual cleanup is needed. Error: %(msg)s Code: %(code)s."
msgstr ""
"Připojení mezi svazkem %(vol)s a hostitelem %(host)s bylo možná navázáno, "
"ale pokus o jeho ukončení selhalo. Ověřte připojení a zjistěte, zdali je "
"třeba zakročit ručně. Chyba: %(msg)s, kóde: %(code)s."

#, python-format
msgid "Connection to libvirt failed: %s"
msgstr "Připojení k libvirt selhalo: %s"

#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Nelze svázat %(host)s:%(port)s"

msgid "Could not decode scheduler options"
msgstr "Nelze rozšifrovat volby plánovače"

#, python-format
msgid ""
"Could not disconnect encrypted volume %(volume)s. If dm-crypt device is "
"still active it will have to be destroyed manually for cleanup to succeed."
msgstr ""
"Nelze odpojit zašifrovaný svazek %(volume)s. Pokud je zařízení dm-crypt "
"stále aktivní, bude muset být odstraněno ručně, aby mohlo být vyčištění "
"úspěšně dokončeno."

#, python-format
msgid "Could not remove tmpdir: %s"
msgstr "Nelze odstranit dočasný adresář: %s"

#, python-format
msgid "Could not start encryption for disk %(device)s: %(exception)s"
msgstr "Nelze spustit šifrování na disku %(device)s: %(exception)s"

#, python-format
msgid "Could not stat scheduler options file %(filename)s"
msgstr "Nelze vyhodnotit soubor voleb plánovače %(filename)s"

msgid "Couldn't communicate with any cells"
msgstr "Nelze komunikovat s žádnou buňkou"

#, python-format
msgid "Couldn't communicate with cell '%s'"
msgstr "Nelze komunikovat s buňkou '%s'"

#, python-format
msgid "Couldn't lookup app: %s"
msgstr "Nelze vyhledat aplikaci: %s"

#, python-format
msgid "Couldn't unmount the GlusterFS share %s"
msgstr "Nelze odpojit sdílení GlusterFS %s"

#, python-format
msgid "Couldn't unmount the NFS share %s"
msgstr "Nelze odpojit sdílení NFS %s"

#, python-format
msgid "Couldn't unmount the Quobyte Volume at %s"
msgstr "Nelze odpojit svazek Quobyte na %s"

#, python-format
msgid "Couldn't unmount the share %s"
msgstr "Nelze odpojit sdílení %s"

#, python-format
msgid "Creating config drive failed with error: %s"
msgstr "Vytváření konfigurační jednotky selhalo s chybou: %s"

msgid "DB error"
msgstr "Chyba DB"

msgid "Destroy VM failed"
msgstr "Zničení VM selhalo"

msgid "Destroy instance failed"
msgstr "Zničení instance selhalo"

#, python-format
msgid "Detaching network adapter failed. Exception: %s"
msgstr "Odpojování síťového adaptéru selhalo. Výjimka: %s"

#, python-format
msgid ""
"Download handler '%(handler)s' raised an exception, falling back to default "
"handler '%(default_handler)s'"
msgstr ""
"Obslužná rutina stažení '%(handler)s' zahlásila výjimku, bude použit výchozí "
"obslužná rutina '%(default_handler)s'"

msgid "Download image error"
msgstr "Chyba stažení obrazu"

#, python-format
msgid "Driver failed to attach volume %(volume_id)s at %(mountpoint)s"
msgstr "Ovladač nemohl připojit svazek %(volume_id)s k %(mountpoint)s"

msgid "Environment variable 'NETWORK_ID' must be set."
msgstr "Proměnná prostředí 'NETWORK_ID' musí být nastavena."

#, python-format
msgid ""
"Error contacting glance server '%(server)s' for '%(method)s', %(extra)s."
msgstr ""
"Chyba při kontaktování serveru glance '%(server)s' pro '%(method)s', "
"%(extra)s."

#, python-format
msgid "Error defining a domain with XML: %s"
msgstr "Chyba při určování domény pomocí XML: %s"

#, python-format
msgid "Error defining a secret with XML: %s"
msgstr "Chyba při určení tajného klíče pomocí XML: %s"

#, python-format
msgid "Error deleting conntrack entries for %s"
msgstr "Chyba při mazání položek conntrack pro %s"

#, python-format
msgid "Error deploying instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Chyba při nasazování instance %(instance)s na uzlu bez operačního systému "
"%(node)s "

#, python-format
msgid "Error enabling hairpin mode with XML: %s"
msgstr "Chyba při povolení režimu spony pomocí XML: %s"

#, python-format
msgid "Error from last host: %(last_host)s (node %(last_node)s): %(exc)s"
msgstr ""
"Chyba od posledního hostitele: %(last_host)s (uzel %(last_node)s): %(exc)s"

#, python-format
msgid "Error from libvirt during destroy. Code=%(errcode)s Error=%(e)s"
msgstr "Chyba od libvirt během ničení. Kód=%(errcode)s Chyba=%(e)s"

#, python-format
msgid "Error from libvirt during undefine. Code=%(errcode)s Error=%(e)s"
msgstr "Chyba od libvirt během rušení určení. Kód=%(errcode)s Chyba=%(e)s"

#, python-format
msgid "Error from libvirt during unfilter. Code=%(errcode)s Error=%(e)s"
msgstr "Chyba od libvirt během rušení filtru. Kód=%(errcode)s Chyba=%(e)s"

#, python-format
msgid ""
"Error from libvirt while injecting an NMI to %(instance_uuid)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""
"Chyba od libvirt při vkládání NMI do %(instance_uuid)s: [Kód chyby "
"%(error_code)s] %(ex)s"

#, python-format
msgid "Error injecting data into image %(img_id)s (%(e)s)"
msgstr "Chyba při vkládání dat do obrazu %(img_id)s (%(e)s)"

#, python-format
msgid "Error instantiating %(provider)s: %(exception)s"
msgstr "Chyba vytváření instance %(provider)s: %(exception)s"

#, python-format
msgid "Error launching a defined domain with XML: %s"
msgstr "Chyba při spouštění určené domény pomocí XML: %s"

msgid "Error locating next hop for message"
msgstr "Chyba při nalezení dalšího skoku zprávy"

msgid "Error locating next hops for message"
msgstr "Chyba při hledání dalších skoků pro zprávu"

msgid ""
"Error occurred during volume_snapshot_create, sending error status to Cinder."
msgstr ""
"Během vytváření snímku svazku došlo k chybě, stav chyby odeslán na Cinder."

msgid ""
"Error occurred during volume_snapshot_delete, sending error status to Cinder."
msgstr ""
"Během mazání snímku svazku došlo k chybě, stav chyby odeslán na Cinder."

#, python-format
msgid "Error on '%(path)s' while checking direct I/O: '%(ex)s'"
msgstr "Chyba v '%(path)s' při kontrole přímého vstupu/výstupu: '%(ex)s'"

#, python-format
msgid ""
"Error preparing deploy for instance %(instance)s on baremetal node %(node)s."
msgstr ""
"Chyba při přípravě na nasazení instance %(instance)s na uzlu bez operačního "
"systému %(node)s."

msgid "Error processing message locally"
msgstr "Chyba při místním zpracování zpráv"

#, python-format
msgid "Error releasing DHCP for IP %(address)s with MAC %(mac_address)s"
msgstr ""
"Chyba při uvolňování DHCP pro IP adresu %(address)s s MAC %(mac_address)s"

#, python-format
msgid "Error scheduling instances %(instance_uuids)s"
msgstr "Chyba při plánování instancí %(instance_uuids)s"

msgid "Error sending message to next hops."
msgstr "Chyba při odesílání zprávy do dalších skoků"

#, python-format
msgid "Error starting xvp: %s"
msgstr "Chyba při spouštění xvp: %s"

msgid "Error trying to Rescue Instance"
msgstr "Chyba při pokusu o záchranu instance"

msgid "Error trying to reschedule"
msgstr "Chyba při pokusu o znovu naplánování"

msgid "Error waiting for responses from neighbor cells"
msgstr "Chyba při čekání na odpověď od sousedních buněk"

#, python-format
msgid "Error while trying to clean up image %s"
msgstr "Chyba při pokusu o vyčištění obrazu %s"

#, python-format
msgid "Error writing to %(path)s: %(exception)s"
msgstr "Chyba při zápisu do %(path)s: %(exception)s"

#, python-format
msgid "Error: %s"
msgstr "Chyba: %s"

#, python-format
msgid "Exception dispatching event %(event)s: %(ex)s"
msgstr "Výjimka při vysílání události %(event)s: %(ex)s"

#, python-format
msgid "Exception handling resource: %s"
msgstr "Obsluhování výjimky zdroje: %s"

msgid "Exception in string format operation"
msgstr "Výjimka při operaci s formátem řetězce"

msgid "Exception loading extension"
msgstr "Výjimka během načítání rozšíření"

#, python-format
msgid "Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Výjimka při spuštění %(name)s %(type)s-hák: %(obj)s"

msgid "Exception while creating table."
msgstr "Výjimka při vytváření tabulky."

#, python-format
msgid "Exception while waiting completion of volume snapshots: %s"
msgstr "Vyskytla se výjimka během čekání na dokončení snímků svazku: %s"

#, python-format
msgid "Extending virtual disk failed with error: %s"
msgstr "Rozšiřování virtuálního disku selhalo s chybou: %s"

#, python-format
msgid "Failed removing bridge device: '%s'"
msgstr "Nelze odstranit zařízení mostu: '%s'"

#, python-format
msgid "Failed removing net device: '%s'"
msgstr "Nelze odstranit síťové zařízení: '%s'"

msgid "Failed storing info cache"
msgstr "Ukládání mezipaměti informací selhalo"

msgid ""
"Failed to allocate PCI devices for instance. Unassigning devices back to "
"pools. This should not happen, since the scheduler should have accurate "
"information, and allocation during claims is controlled via a hold on the "
"compute node semaphore"
msgstr ""
"Nelze přidělit zařízení PCI k instanci. Zařízení jsou navrácena do zásob- "
"Toto by se nemělo dít, protože plánovač by měl mít přesné informace a "
"přidělení během nárokování je ovládáno uzmutím semaforu výpočetního uzlu."

msgid "Failed to allocate network(s)"
msgstr "Nelze přidělit síť(ě)"

#, python-format
msgid "Failed to attach %(volume_id)s at %(mountpoint)s"
msgstr "Nelze připojit %(volume_id)s na %(mountpoint)s"

#, python-format
msgid "Failed to attach volume at mountpoint: %s"
msgstr "Nelze připojit svazek k bodu připojení: %s"

#, python-format
msgid "Failed to change vm state of %(instance_name)s to %(req_state)s"
msgstr "Nelze změnit stav vm v %(instance_name)s na %(req_state)s"

msgid "Failed to check if instance shared"
msgstr "Nelze zkontrolovat sdílení instance"

#, python-format
msgid "Failed to cleanup directory %(target)s: %(e)s"
msgstr "Nelze vyčistit adresář %(target)s: %(e)s"

msgid "Failed to cleanup snapshot."
msgstr "Nelze vyčistit snímek."

#, python-format
msgid "Failed to commit reservations %s"
msgstr "Nelze odevzdat rezervaci %s"

msgid "Failed to complete a deletion"
msgstr "Nelze dokončit smazání"

#, python-format
msgid "Failed to connect to volume %(volume_id)s with volume at %(mountpoint)s"
msgstr ""
"Nelze se připojit k svazku %(volume_id)s pomocí svazku na %(mountpoint)s"

#, python-format
msgid ""
"Failed to copy cached image %(source)s to %(dest)s for resize: %(error)s"
msgstr ""
"Nelze zkopírovat snímek v mezipaměti %(source)s do %(dest)s pro změnu "
"velikosti: %(error)s"

msgid "Failed to deallocate networks"
msgstr "Nelze zrušit přidělení sítí"

#, python-format
msgid "Failed to decrypt %(image_location)s to %(image_path)s"
msgstr "Nelze dešifrovat %(image_location)s do %(image_path)s"

#, python-format
msgid "Failed to destroy instance: %s"
msgstr "Nelze zničit instanci: %s"

#, python-format
msgid "Failed to detach %(device_name)s. Exception: %(exc)s"
msgstr "Nelze odpojit %(device_name)s. Výjimka: %(exc)s"

#, python-format
msgid "Failed to detach volume %(volume_id)s from %(mp)s"
msgstr "Nelze odpojit svazek %(volume_id)s z %(mp)s"

#, python-format
msgid "Failed to download %(image_location)s to %(image_path)s"
msgstr "Nelze stáhnout %(image_location)s do %(image_path)s"

#, python-format
msgid ""
"Failed to extract compute RPC version from service history because I am too "
"old (minimum version is now %(version)i)"
msgstr ""
"Nelze extrahovat verzi výpočetní RPC z historii služeb, protože je příliš "
"stará. (Minimální verze je nyní %(version)i)"

#, python-format
msgid ""
"Failed to extract compute RPC version from service history for version "
"%(version)i"
msgstr ""
"Nelze extrahovat verzi výpočetní RPC z historii služeb, pro verzi %(version)i"

msgid "Failed to fetch glance image"
msgstr "Nelze získat obraz glance"

#, python-format
msgid "Failed to find an SR for volume %s"
msgstr "Nelze najít SR pro svazek %s"

#, python-format
msgid "Failed to forget the SR for volume %s"
msgstr "Nelze zapomenout SR svazku %s"

#, python-format
msgid "Failed to generate usage audit for instance on host %s"
msgstr "Nelze vytvořit kontrolu využití pro instanci na hostiteli %s"

#, python-format
msgid "Failed to get compute_info for %s"
msgstr "Nelze získat informace o výpočtu pro %s"

msgid "Failed to get default networks"
msgstr "Nelze získat výchozí sítě"

#, python-format
msgid ""
"Failed to get instance id for metadata request, provider %(provider)s "
"networks %(networks)s requester %(requester)s. Error: %(error)s"
msgstr ""
"Nelze získat id instance pro žádost o popisná data, poskytovatel "
"%(provider)s, sítě %(networks)s, žadatel %(requester)s. Chyba: %(error)s"

#, python-format
msgid "Failed to get metadata for instance id: %s"
msgstr "Nelze získat popisná data pro id instance: %s"

msgid "Failed to get nw_info"
msgstr "Nelze získat informace o síti"

#, python-format
msgid "Failed to instantiate the download handler for %(scheme)s"
msgstr "Nelze zavést obslužnou rutinu stažení pro %(scheme)s"

#, python-format
msgid ""
"Failed to kill process %(pid)s due to %(reason)s, while deleting the "
"instance."
msgstr "Nelze ukončit proces %(pid)s kvůli %(reason)s, při mazání instance"

#, python-format
msgid "Failed to load %(cfgfile)s: %(ex)s"
msgstr "Nelze načíst %(cfgfile)s: %(ex)s"

#, python-format
msgid "Failed to load %s"
msgstr "Nelze načíst %s"

#, python-format
msgid "Failed to load %s-api"
msgstr "Nelze načíst %s-api"

#, python-format
msgid ""
"Failed to mount container filesystem '%(image)s' on '%(target)s': %(errors)s"
msgstr ""
"Nelze připojit souborový systém kontejneru '%(image)s' v '%(target)s': "
"%(errors)s"

msgid "Failed to notify cells of BDM destroy."
msgstr "Nelze oznámit buňkám zničení BDM."

msgid "Failed to notify cells of BDM update/create."
msgstr "Nelze oznámit buňkám aktualizaci/vytvoření BDM."

msgid "Failed to notify cells of bw_usage update"
msgstr "Nelze buňkám oznámit aktualizaci využití šířky pásma"

msgid "Failed to notify cells of instance fault"
msgstr "Nelze buňkám oznámit chybu instance"

msgid "Failed to notify cells of instance info cache update"
msgstr "Nelze buňkám oznámit aktualizaci mezipaměti informací instance"

#, python-format
msgid "Failed to remove %(base_file)s, error was %(error)s"
msgstr "Nelze odstranit %(base_file)s, chyba byla %(error)s"

#, python-format
msgid "Failed to request Ironic to provision instance %(inst)s: %(reason)s"
msgstr "Nelze zažádat Ironic o poskytnutí instance %(inst)s: %(reason)s"

#, python-format
msgid ""
"Failed to retrieve encryption metadata for volume %(volume_id)s: "
"%(exception)s"
msgstr ""
"Nelze získat popisná data šifrování svazku %(volume_id)s: %(exception)s"

msgid "Failed to retrieve ephemeral encryption key"
msgstr "Nelze získat efemerní šifrovací klíč"

msgid "Failed to revert crashed migration"
msgstr "Nelze vrátit nezdařené přesunutí"

#, python-format
msgid "Failed to roll back reservations %s"
msgstr "Nelze vrátit zpět rezervaci %s"

msgid "Failed to rollback quota for failed finish_resize"
msgstr "Nelze vrátit zpět kvótu pro neúspěšné dokončení změny velikosti"

#, python-format
msgid "Failed to send message to cell: %(next_hop)s"
msgstr "Nelze odeslat zprávu buňce: %(next_hop)s"

msgid "Failed to send state update notification"
msgstr "Nelze odeslat oznámení o aktualizaci stavu"

msgid "Failed to send updated snapshot status to volume service."
msgstr "Nelze odeslat aktualizovaný stav snímku do služby svazku."

msgid "Failed to set instance name using multi_instance_display_name_template."
msgstr ""
"Nelze nastavit název instance pomocí multi_instance_display_name_template."

#, python-format
msgid "Failed to start %(name)s on %(host)s:%(port)s with SSL support"
msgstr "Nelze spustit %(name)s na %(host)s:%(port)s s podporou SSL"

msgid "Failed to start instance"
msgstr "Nelze spustit instanci"

msgid "Failed to stop instance"
msgstr "Nelze zastavit instance"

#, python-format
msgid "Failed to swap volume %(old_volume_id)s for %(new_volume_id)s"
msgstr "Nelze vyměnit svazek %(old_volume_id)s za %(new_volume_id)s"

msgid "Failed to teardown container filesystem"
msgstr "Nelze strhnout souborový systém kontejneru"

msgid "Failed to umount container filesystem"
msgstr "Nelze odpojit souborový systém kontejneru"

msgid "Failed to unpause instance"
msgstr "Nelze zrušit pozastavení iínstance"

#, python-format
msgid "Failed to untar %(image_location)s to %(image_path)s"
msgstr "Nelze rozbalit %(image_location)s do %(image_path)s"

msgid "Failed to update usages bulk deallocating floating IP"
msgstr ""
"Nelze aktualizovat využití při hromadném rušení přidělení plovoucích IP"

msgid "Failed to update usages deallocating fixed IP"
msgstr "Nelze aktualizovat využití při rušení přidělení pevných IP adres"

msgid "Failed to update usages deallocating floating IP"
msgstr "Nelze aktualizovat využití při rušení přidělení plovoucí IP adresy"

msgid "Failed to update usages deallocating network."
msgstr "Nelze aktualizovat využití při rušení přidělení sítě."

msgid "Failed to update usages deallocating security group"
msgstr "Nelze aktualizovat využití při rušení přidělení bezpečnostní skupiny"

msgid "Failed to update usages deallocating server group"
msgstr "Nelze aktualizovat využití při rušení přidělení skupiny serveru"

#, python-format
msgid "Failed to upload %(image_location)s to %(image_path)s"
msgstr "Nelze nahrát %(image_location)s do %(image_path)s"

msgid "Failed to write configuration file"
msgstr "Nelze zapsat soubor s nastavením"

msgid "Failed to write inbound.csr"
msgstr "Nelze zapisovat do inbound.csr"

msgid "Failed while plugging ib hostdev vif"
msgstr "Zapojování ib hostdev virtuálního rozhraní selhalo"

msgid "Failed while plugging vif"
msgstr "Zapojování virtuálního rozhraní selhalo"

msgid "Failed while unplugging ib hostdev vif"
msgstr "Odpojování ib hostdev virtuálního rozhraní selhalo"

msgid "Failed while unplugging vif"
msgstr "Odpojení virtuálního rozhraní selhalo"

msgid "Failure prepping block device"
msgstr "Chyba při přípravě blokového zařízení"

msgid "Failure while cleaning up attached VDIs"
msgstr "Čištění připojených VDI selhalo"

#, python-format
msgid "Fatal Exception running %(name)s %(type)s-hook: %(obj)s"
msgstr "Závažná výjimka při spuštění %(name)s %(type)s-hák: %(obj)s"

msgid "Guest does not have a console available"
msgstr "Host nemá konzoli k dispozici"

msgid "Host is member of a pool, but DB says otherwise"
msgstr "Hostitel je členem zásoby, ale databáze sděluje něco jiného"

#, python-format
msgid ""
"Hostname has changed from %(old)s to %(new)s. A restart is required to take "
"effect."
msgstr ""
"Název hostitele změněn z %(old)s na %(new)s. Aby změny nabyly účinku, je "
"třeba restartovat."

#, python-format
msgid "Image size %(size)d exceeded flavor allowed size %(allowed_size)d"
msgstr ""
"Velikost obrazu %(size)d překročila množství %(allowed_size)d povolené "
"konfigurací"

#, python-format
msgid "Improper or unknown HTTP status code used: %d"
msgstr "Použit nesprávný nebo špatný kód stavu HTTP: %d"

#, python-format
msgid ""
"Initialize connection failed for volume %(vol)s on host %(host)s. Error: "
"%(msg)s Code: %(code)s. Attempting to terminate connection."
msgstr ""
"Zavedení připojení selhalo u svazku %(vol)s na hostiteli %(host)s. Chyba: "
"%(msg)s, kód: %(code)s. Probíhá pokus o přerušení připojení."

#, python-format
msgid ""
"Instance compute service state on %s expected to be down, but it was up."
msgstr ""
"Stav výpočetní služby instance na %s byl považován za \"Vypnuto\", ale místo "
"toho bylo \"Zapnuto\"."

msgid "Instance failed block device setup"
msgstr "Instance selhala nastavit blokového zařízení"

#, python-format
msgid "Instance failed network setup after %(attempts)d attempt(s)"
msgstr "Instance nemohla nastavit síť po %(attempts)d pokusech"

msgid "Instance failed to spawn"
msgstr "Instance nemohla být spuštěna"

#, python-format
msgid "Interface %s not found"
msgstr "Rozhraní %s nenalezeno"

#, python-format
msgid "Invalid server_string: %s"
msgstr "Neplatný řetězec serveru: %s"

#, python-format
msgid "Live Migration failure: %s"
msgstr "Selhání přesunu za běhu: %s"

msgid "Live migration failed."
msgstr "Přesun za provozu selhal."

msgid "Migrate Receive failed"
msgstr "Přijetí přesunu selhalo"

msgid "Migrate Send failed"
msgstr "Odeslání přesunu selhalo"

#, python-format
msgid "Migration %s is not found during confirmation"
msgstr "Přesun %s nebyl během potvrzování nalezen"

#, python-format
msgid ""
"Migration of instance %(instance_id)s to host %(dest)s unexpectedly failed."
msgstr ""
"Přesun instance %(instance_id)s na hostitele %(dest)s neočekávaně selhal."

msgid "Migration operation has aborted"
msgstr "Operace přesunu byla ukončena"

#, python-format
msgid "NBD error - previous umount did not cleanup /var/lock/qemu-nbd-%s."
msgstr "Chyba NBD . předchozí odpojení nevyčistilo /var/lock/qemu-nbd-%s."

#, python-format
msgid ""
"NOT IMPLEMENTED: The call to %(method)s is not supported by the agent. args="
"%(args)r"
msgstr ""
"NEZAVEDENO: Volání %(method)s není agentem podporováno. argumenty=%(args)r"

msgid "Network driver option required, but not specified"
msgstr "Vyžadována volba ovladače sítě, ale žádná nebyla zadána"

#, python-format
msgid "Neutron Error adding rules to security group %s"
msgstr "Chyba Neutron při přidávání pravidel do bezpečnostní skupiny %s"

#, python-format
msgid "Neutron Error creating security group %s"
msgstr "Chyba Neutron při vytváření bezpečnostní skupiny %s"

#, python-format
msgid "Neutron Error getting security group %s"
msgstr "Chyba Neutron při získávání bezpečnostní skupiny %s"

msgid "Neutron Error getting security groups"
msgstr "Chyba Neutron při získávání bezpečnostních skupin"

#, python-format
msgid "Neutron Error unable to delete %s"
msgstr "Chyba Neutron: nelze smazat %s"

#, python-format
msgid "Neutron Error updating security group %s"
msgstr "Chyba Neutron při aktualizaci bezpečnostní skupiny %s"

msgid "Neutron Error:"
msgstr "Chyba Neutron:"

#, python-format
msgid "Neutron Error: %s"
msgstr "Chyba Neutron: %s"

#, python-format
msgid "Neutron Reported failure on event %(event)s for instance %(uuid)s"
msgstr "Neutron nahlásil chybu události %(event)s v instanci %(uuid)s"

#, python-format
msgid "Neutron error creating port on network %s"
msgstr "Chyba Neutron při vytváření portu na síti %s"

#, python-format
msgid "No compute node record for host %s"
msgstr "nenalezen žádný záznam výpočetního uzle pro hostitele %s"

#, python-format
msgid "No save handler for %s"
msgstr "Žádná obslužná rutina pro uložení %s"

msgid "Not all properties needed are implemented in the compute driver"
msgstr "Ne všechny potřebné vlastnosti jsou ovladačem výpočtu zavedeny"

msgid ""
"Periodic sync_power_state task had an error while processing an instance."
msgstr ""
"Periodický úkol synchronizace stavu napájení narazil na chybu při zpracování "
"instance."

msgid "Periodic task failed to offload instance."
msgstr "Pravidelný úkol nemohl převést zátěž instance."

msgid "Plugin config_file get_val failed"
msgstr "Získání hodnoty z konfiguračního souboru zásuvného modulu selhalo"

#, python-format
msgid "Pool-Join failed: %s"
msgstr "Připojení zásoby selhalo: %s"

#, python-format
msgid "Pool-eject failed: %s"
msgstr "Odpojení zásoby selhalo: %s"

#, python-format
msgid "Pool-set_name_label failed: %s"
msgstr "Nastavení štítku názvu zásoby selhalo: %s"

#, python-format
msgid "Pre live migration failed at %s"
msgstr "Příprava přesunu za provozu selhala v %s"

msgid "Read/Write data failed"
msgstr "Zápis/Čtení dat selhalo"

#, python-format
msgid "Requested VM Generation %s is not supported on this OS."
msgstr "Požadované vytvoření VM %s není v tomto OS podporováno."

#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr "Požadováno vytvoření VM %s ale je zadáno VHD místo VHDX."

#, python-format
msgid "Returning exception %s to caller"
msgstr "Volajícímu je vrácena výjimka: %s"

msgid "Service error occurred during cleanup_host"
msgstr "Během čištění hostitele došlo k chybě služby"

msgid "Setting instance vm_state to ERROR"
msgstr "Nastavování stavu vm instance na CHYBA"

msgid "Shutting down VM (cleanly) failed."
msgstr "(Čisté) Vypnutí VM selhalo."

msgid "Shutting down VM (hard) failed"
msgstr "(Tvrdé) Vypnutí VM selhalo"

msgid ""
"Something wrong happened when trying to delete snapshot from shelved "
"instance."
msgstr "Při mazání snímku z uskladněné instance se něco zvrtlo."

#, python-format
msgid "TIMEOUT: The call to %(method)s timed out. args=%(args)r"
msgstr "ČASOVÝ LIMIT: Vypršel čas volání %(method)s. argumenty=%(args)r"

#, python-format
msgid "Temporary directory is invalid: %s"
msgstr "Dočasný adresář je neplatný: %s"

#, python-format
msgid "The Quobyte volume at %s is still in use."
msgstr "Svazek Quobyte na %s se stále používá."

#, python-format
msgid "The agent call to %(method)s returned an error: %(ret)r. args=%(args)r"
msgstr "Volání agenta %(method)s vrátilo chybu: %(ret)r. argumenty=%(args)r"

#, python-format
msgid ""
"The agent call to %(method)s returned an invalid response: %(ret)r. args="
"%(args)r"
msgstr ""
"Volání agenta %(method)s vrátilo neplatnou odpověď: %(ret)r. argumenty="
"%(args)r"

#, python-format
msgid "The call to %(method)s returned an error: %(e)s."
msgstr "Volání %(method)s vrátilo chybu: %(e)s."

#, python-format
msgid "The call to %(method)s returned an error: %(e)s. args=%(args)r"
msgstr "Volání %(method)s vrátilo chybu: %(e)s. argumenty=%(args)r"

msgid "Transfer data failed"
msgstr "Přenos dat selhal"

#, python-format
msgid "Unable to access floating IP %s"
msgstr "Nelze získat přístup k plovoucím IP %s"

#, python-format
msgid "Unable to access floating IP for %s"
msgstr "Nelze získat přístup k plovoucím IP pro %s"

msgid "Unable to access the rescue disk"
msgstr "Nelze získat přístup k záchrannému disku"

#, python-format
msgid "Unable to attach volume to instance %s"
msgstr "Nelze připojit svazek k instanci %s"

#, python-format
msgid "Unable to clear device ID for port '%s'"
msgstr "Nelze vyčistit ID zařízení pro port '%s'"

msgid "Unable to create VM snapshot, failing volume_snapshot operation."
msgstr ""
"Nelze vytvořit snímek VM, přechází se zpět na operaci se snímkem svazku"

msgid ""
"Unable to create quiesced VM snapshot, attempting again with quiescing "
"disabled."
msgstr ""
"Nelze vytvořit ztišený snímek VM, bude uskutečně další pokus, kde ztišení "
"bude zakázáno."

msgid "Unable to destroy VBD"
msgstr "Nelze zničit VBD"

#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr "Nelze spustit %(cmd)s. Výjimka: %(exception)s"

msgid "Unable to find SR from VBD"
msgstr "Nelze najít SR z VBD"

msgid "Unable to find SR from VDI"
msgstr "Nelze najít SR z VDI"

msgid "Unable to get record of VDI"
msgstr "Nelze získat záznam VDI"

msgid "Unable to get updated status"
msgstr "Nelze získat aktualizovaný stav"

msgid "Unable to introduce VDI for SR"
msgstr "Nelze zavést VDI pro SR"

msgid "Unable to introduce VDI on SR"
msgstr "Nelze zavést VDI na SR"

msgid "Unable to load the virtualization driver"
msgstr "Nelze načíst ovladač virtualiazce"

#, python-format
msgid "Unable to migrate VM %(vm_ref)s from %(host)s"
msgstr "Nelze přesunout VM %(vm_ref)s z %(host)s"

#, python-format
msgid ""
"Unable to obtain RRD XML for VM %(vm_uuid)s with server details: %(server)s."
msgstr ""
"Nelze získat RRD XML pro VM %(vm_uuid)s mající podrobnosti serveru: "
"%(server)s."

#, python-format
msgid "Unable to parse rrd of %s"
msgstr "Nelze zpracovat rrd z %s"

#, python-format
msgid "Unable to retrieve certificate with ID %(id)s: %(e)s"
msgstr "Nelze získat certifikát s ID %(id)s: %(e)s"

#, python-format
msgid "Unable to retrieve storage policy with name %s"
msgstr "Nelze získat zásady úložiště s názvem %s"

#, python-format
msgid "Unable to set up pool: %s."
msgstr "Nelze vytvořit zásobu: %s"

msgid "Unable to unplug VBD"
msgstr "Nelze odpojit VBD"

#, python-format
msgid "Unable to update instance VNIC index for port %s."
msgstr "Nelze aktualizovat index VNIC instance pro port %s."

msgid "Unexpected build failure, not rescheduling build."
msgstr "Neočekávané selhání sestavení, nebude znovu naplánováno."

#, python-format
msgid "Unexpected error while checking process %(pid)s."
msgstr "Neočekávaná chyba při kontrole procesu %(pid)s."

msgid "Unexpected error while reporting service status"
msgstr "Při hlášení stavu služby se objevila nečekaná chyba."

msgid "Unexpected exception in API method"
msgstr "Neočekávaná výjimka v metodě API"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capabilities"
msgstr "Neznámá buňka '%(cell_name)s' při pokusu o aktualizaci schopností"

#, python-format
msgid "Unknown cell '%(cell_name)s' when trying to update capacities"
msgstr "Neznámá buňka '%(cell_name)s' při pokusu o aktualizaci kapacit"

#, python-format
msgid "Unknown content in connection_info/access_mode: %s"
msgstr "Neznámý obsah v informacích o připojení/režimu přístupu: %s"

msgid "Unshelve attempted but an error has occurred"
msgstr "Pokus o vyskladnění skončil objevem chyby"

msgid "Unshelve attempted but vm_state not SHELVED or SHELVED_OFFLOADED"
msgstr ""
"Pokus o vyskladnění ale stav vm není USKLADNĚN nebo USKLADNĚN S PŘEVEDENOU "
"ZÁTĚŽÍ"

msgid "Vifs plug failed"
msgstr "Zapojení virtuálního rozhraní selhalo"

#, python-format
msgid "Volume %s is associated with the instance but no SR was found for it"
msgstr ""
"Svazek %s je přidružen k instanci, ale nebylo pro něj nalezeno žádné SR"

#, python-format
msgid "Volume is not writable. Please broaden the file permissions. Mount: %s"
msgstr ""
"Nelze zapisovat na svazek. Prosím rozšiřte oprávnění souboru. Připojení: %s"

#, python-format
msgid ""
"When loading the module %(module_str)s the following error occurred: %(ex)s"
msgstr ""
"Při načítání modulu %(module_str)s se objevila následující chyba: %(ex)s "

msgid ""
"XenAPI is unable to find a Storage Repository to install guest instances on. "
"Please check your configuration (e.g. set a default SR for the pool) and/or "
"configure the flag 'sr_matching_filter'."
msgstr ""
"XenAPI nemohlo najít repozitář úložišť na které instalovat hosty. Prosím "
"zkontrolujte své nastavení (např. nastavte výchozí SR pro zásobu) a/nebo "
"nastavte příznak 'sr_matching_filter'."

msgid ""
"You are running nova-compute on an unsupported version of Windows (older "
"than Windows / Hyper-V Server 2012). The support for this version of Windows "
"has been removed in Mitaka."
msgstr ""
"nova-compute spouštíte na nepodporované verzi Windows (starší než Windows / "
"Hyper-V Server 2012). Podpora pro tuto verzi byla odstraněna v Mitaka."

msgid "_migrate_disk_resizing_down failed. Restoring orig vm"
msgstr "Přesunutí a zmenšení disku selhalo. Obnovování původní vm"

#, python-format
msgid "_migrate_disk_resizing_up failed. Restoring orig vm due_to: %s."
msgstr "Přesunutí a zvětšení disku selhalo. Obnovování původní vm kvůli: %s"

#, python-format
msgid "allocate_port_for_instance returned %(ports)s ports"
msgstr "přidělení portu pro instanci vrátilo %(ports)s portů"

msgid "attaching network adapter failed."
msgstr "připojování síťového adaptéru selhalo."

msgid "detaching network adapter failed."
msgstr "odpojování síťového adaptéru selhalo."

msgid "error during stop() in sync_power_state."
msgstr "chyba během stop() v synchronizaci stavu napájení."

#, python-format
msgid "error opening rbd image %s"
msgstr "chyba při otevírání obrazu rbd %s"

#, python-format
msgid "image %(volume)s in pool %(pool)s has snapshots, failed to remove"
msgstr "obraz %(volume)s v zásobě %(pool)s má snímky, nelze odstranit"

#, python-format
msgid "kill -HUP dnsmasq threw %s"
msgstr "kill -HUP dnsmasq vypsal %s"

#, python-format
msgid "killing radvd threw %s"
msgstr "ukončení radvd vrhlo %s"

msgid "nbd module not loaded"
msgstr "modul nbd nenačten"

msgid "set_admin_password failed"
msgstr "nastavení hesla správce selhalo"

#, python-format
msgid ""
"status is UNKNOWN from vm_state=%(vm_state)s task_state=%(task_state)s. Bad "
"upgrade or db corrupted?"
msgstr ""
"stav je NEZNÁMÝ, stav vm=%(vm_state)s, stav úkolu=%(task_state)s. Špatná "
"aktualizace nebo poškozená db?"
